# 01-storage-and-secrets.yaml
---
# SECRET: Menyimpan kata sandi database
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  # Ganti dengan kata sandi Anda
  mysql-root-password: 
  mysql-password: 
  mysql-user: wordpress
  mysql-database: wordpress
---
# PERSISTENT VOLUME CLAIM (PVC) untuk MySQL
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
# PERSISTENT VOLUME CLAIM (PVC) untuk WordPress
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi